USE SAKILA;

SELECT * FROM  ACTOR;
SELECT * FROM  ADDRESS;
SELECT * FROM  CATEGORY;
SELECT * FROM  CITY;
SELECT * FROM  COUNTRY;
SELECT * FROM  CUSTOMER;
SELECT * FROM  FILM;
SELECT * FROM  FILM_ACTOR;
SELECT * FROM  FILM_CATEGORY;
SELECT * FROM  FILM_TEXT;
SELECT * FROM  INVENTORY;
SELECT * FROM  LANGUAGE;
SELECT * FROM  PAYMENT;
SELECT * FROM  RENTAL;
SELECT * FROM  STAFF;
SELECT * FROM  STORE;





